version: '3.8'

services:
  postgres:
    image: postgis/postgis:16-master
    environment:
      POSTGRES_USER: openadvocacy
      POSTGRES_PASSWORD: devpassword
      POSTGRES_DB: openadvocacy
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    depends_on:
      - postgres
    environment:
      - DATABASE_PROVIDER=postgres
      - DATABASE_URL=postgresql+asyncpg://openadvocacy:devpassword@postgres:5432/openadvocacy
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data: